with debug in test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,55 +7,55 @@ on:
     branches: ["master"]
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    services:
-      gilgoblin-database:
-        image: nickreinlein/gilgoblin-database
-        env:
-          POSTGRES_DB: gilgoblin_db
-          POSTGRES_USER: gilgoblin
-          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
-        ports:
-          - 5432:5432
-        options: >-
-          --health-cmd "pg_isready -d gilgoblin_db -U gilgoblin"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
+  # build:
+  #   runs-on: ubuntu-latest
+  #   services:
+  #     gilgoblin-database:
+  #       image: nickreinlein/gilgoblin-database
+  #       env:
+  #         POSTGRES_DB: gilgoblin_db
+  #         POSTGRES_USER: gilgoblin
+  #         POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
+  #       ports:
+  #         - 5432:5432
+  #       options: >-
+  #         --health-cmd "pg_isready -d gilgoblin_db -U gilgoblin"
+  #         --health-interval 10s
+  #         --health-timeout 5s
+  #         --health-retries 5
 
-    steps:
-      - uses: actions/checkout@v4
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - name: Setup .NET8
-        uses: actions/setup-dotnet@v4
-        with:
-          dotnet-version: 8.0.x
+  #     - name: Setup .NET8
+  #       uses: actions/setup-dotnet@v4
+  #       with:
+  #         dotnet-version: 8.0.x
 
-      - name: Restore dependencies
-        run: dotnet restore
+  #     - name: Restore dependencies
+  #       run: dotnet restore
 
-      - name: Build
-        run: dotnet build --no-restore
+  #     - name: Build
+  #       run: dotnet build --no-restore
 
-      - name: Wait for Database
-        run: |
-          for i in {1..10}; do
-            if pg_isready -h localhost -p 5432; then
-              echo "Database is ready!"
-              exit 0
-            else
-              echo "Waiting for database... ($i/10)"
-              sleep 5
-            fi
-          done
-          echo "Database did not become ready in time."
-          exit 1
+  #     - name: Wait for Database
+  #       run: |
+  #         for i in {1..10}; do
+  #           if pg_isready -h localhost -p 5432; then
+  #             echo "Database is ready!"
+  #             exit 0
+  #           else
+  #             echo "Waiting for database... ($i/10)"
+  #             sleep 5
+  #           fi
+  #         done
+  #         echo "Database did not become ready in time."
+  #         exit 1
 
-      - name: Test
-        env:
-          ConnectionStrings__GilGoblinDbContext: ${{ secrets.DB_CONNECTION_STRING }}
-        run: dotnet test --no-build --verbosity detailed --filter "Category!=Component"
+  #     - name: Test
+  #       env:
+  #         ConnectionStrings__GilGoblinDbContext: ${{ secrets.DB_CONNECTION_STRING }}
+  #       run: dotnet test --no-build --verbosity detailed --filter "Category!=Component"
 
   publish-nuget:
     runs-on: ubuntu-latest
@@ -94,7 +94,10 @@ jobs:
             project_dir=$(dirname "$csproj")
             dotnet pack "$csproj" --configuration Release -o "$project_dir/nupkgs"
             for pkg in "$project_dir/nupkgs/"*.nupkg; do
-              dotnet nuget push "$pkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
+              echo "Pushing package $pkg to NuGet..."
+              dotnet nuget push "$pkg" \
+                --api-key ${{ secrets.NUGET_API_KEY }} \
+                --source https://api.nuget.org/v3/index.json
             done
           done
 
